query($projectId: ID!) {
  node(id: $projectId) {
    ... on ProjectV2 {
      id
      title
      views(first: 20) {
        nodes {
          id
          name
          layout
          number
          verticalGroupBy {
            ... on ProjectV2FieldConfiguration {
              id
              name
            }
          }
          fields(first: 30) {
            nodes {
              ... on ProjectV2FieldConfiguration {
                id
                name
              }
            }
          }
        }
      }
    }
  }
}
